GET http://localhost:8000/movies

###

GET http://localhost:8000/movies/62fa9661d5c991a78540264c

###

POST http://localhost:8000/movies
Content-Type: application/json

{
    "name": "Deadpool",
    "genre": "Comedy",
    "rating": "R"
}

###

DELETE http://localhost:8000/movies/62f94bbbfb9bc1ff778d5f83

###

PATCH http://localhost:8000/movies/62f94bbbfb9bc1ff778d5f81
Content-Type: application/json

{
    "name": "Deadpool 2",
    "genre": "Comedy",
    "rating": "R"
}